<?php
	include_once ( $_SERVER['DOCUMENT_ROOT'] . "/shared/shared.php" );
	create_XMLheader();
?>
<div>
	<h1>Siros</h1>

	<h2>Monat der Liebe</h2>

<p>Der Monat Siros ist nach Sirani benannt, der Göttin der Liebe, die weithin von allen Rassen gefeiert wird. Alle bekannten Kulturen haben Loyalitäts- und Vereinigungsrituale während des Monat Siros und Sirani ist und bleibt sehr populär in Salkamar, Gynk und auch unter den Serinjah. Zumeist jubilante Jahrmärkte oder Tanzfeste, ist jungen Paaren hier die Möglichkeit gegeben, sich zu treffen und womöglich ihre Ehegelübde abzulegen. Es gibt kein genaues Datum für diese Zelebration, jedoch findet sie meistens um den 12. Siros statt. Oft arrangieren die örtlichen Herrscher es so, dass an jedem Tag in einem anderen Dorf ein Fest stattfindet.</p>

<p>Obwohl alle feiern, gibt es zwischen den einzelnen Rassen und Religionen Unterschiede. In elfischer Tradition, bringt der männliche Anwärter Zweige des Mevrannobaumes am Eingang des Hauses seiner Angebeteten an. Der Mevrannobaum lebt in Symbiose mit der Kletterpflanze Levrenni, die sich um Bäume schlingt, wenn diese noch jung sind und wunderschön blühen; alleine kann keine der beiden Pflanzen gedeihen. Wenn die Kandidatin Interesse hat, bindet sie einen Stängel der Levrennipflanze um den Ast des Mevrannobaumes. Unter den Halblingen sind es die Damen, die den ersten Schritt wagen, indem sie einen Kranz aus Blumen auf das Haupt ihres Geliebten legen. Wenn der Mann den Kranz nicht ablegt, gilt das Angebot als angenommen. Menschliche Traditionen sind weitaus komplizierter und sehr viel unterschiedlicher unter den einzelnen Kulturen und oft kein echtes Angebot, als viel mehr ein Ausdruck der Liebe. Dinge, die in einem Dorf als ehrhaft und liebenswert gelten, mögen in einem anderen als überaus beleidigend angesehen werden. Am gebräuchlichsten ist es, dass der Mann seine Angebetete um einen Tanz bittet, aber nicht alle Tänze sind für die Liebe. Sollte die Frau sich zu einem Mann hingezogen fühlen, gibt sie ihm als traditionelles Zeichen ihres Interesses eine Schleife, welche ihr zuvor in ihr Haar geflochten worden war. Wenn der Mann die Schleife um seinen Arm bindet, signalisiert er damit, dass er ihre Gefühle erwidert.</p>

<p>Orks sind bekannt für ihre etwas rauere Art, ihrer Liebe Ausdruck zu verleihen. Nach ihrer Tradition, sucht der Mann gemeinsam mit einem Freund das Haus seiner Angebeteten auf und entführt sie. Da die Entführung sehr rituell abläuft, gibt es für gewöhnlich auf keiner der beiden Seiten Verletzungen, außer wenn die Frau ihren Verehrer bereits zuvor abgelehnt hatte. Für gewöhnlich wird die Entführte sofort zum Haus des Mannes gebracht, während ihre Familie sich draußen versammelt, um sie zu "retten". Wenn die Orkin die Türe öffnet und ihre Familie bittet einzutreten, ehe diese das Haus stürmt, gilt der Heiratsantrag als angenommen. Unter den Echsenmenschen wird die Ehe für gewöhnlich von den Eltern arrangiert und die Kinder haben dabei keinerlei Mitspracherecht. Dadurch ist es durchaus nicht ungewöhnlich, dass das Brautpaar sich am Tage des Fests zum ersten Mal trifft. Die Eltern machen ihre Pläne vor den Festivitäten und dann trifft sich das Paar im Haus des Mannes, ehe alle gemeinsam zum Tempel gehen, wo das Brautpaar vor einem Priester das Gelübde ablegt. Im Falle der Zwerge spielt der Schmied eine wichtige spirituelle Rolle bei der Zeremonie, die über das bloße Schmieden der Ringe hinausgeht. Ein Paar, welches heiraten möchte, wird von einem Schmied "verbunden", der zwei Ringe aus demselben Stück Metall schmiedet, die sich zu einem verbinden, wenn man sie zusammenführt. Traditionell werden diese Ringe über dem Ehebett des Paares angebracht und symbolisieren fortan ihre Verbundenheit und die Stärke, die ihre Vereinigung bringt.</p>

</div>
<?php include_short_footer(); ?>