<?php
	include_once ( $_SERVER['DOCUMENT_ROOT'] . "/shared/shared.php" );
	create_XMLheader();
?>
<div>
	<h1>Mas</h1>

	<h2>Monat des Blutmondes</h2>

<p>Mas, der kürzeste aller Monate, wurde nach Moshran, dem Gott des Blutes und der Knochen benannt. Der Monat des Blutes wird gefürchtet und bringt großes Unglück über ganz Illarion und andere zivilisierte Reiche, wie Albar, Salkamar und Gynk. Während Söldnertruppen diesen Monat als Grund für wilde Trinkgelage und Schlägereien nutzen mögen, feiern einige Orkstämme die Bluttage als Radosh. Der Monat wird voller Freude und Ehrerbietung erwartet, ehe die Orks sich der Ekstase wilder und ungestümer Kämpfe hingeben. Riesige Höhlen werden mit Fackeln und Feuern erleuchtet und zeremonielle Kämpfe werden ausgetragen; es wird allgemein geglaubt, dass viele Dispute und Streitereien in diesen Kämpfen geregelt werden. Generell bleiben die Kämpfe zeremoniell und enden nicht in all zu viel Blut, aber in vielen der am wenigsten zivilisierten Orkstämme, "schlachten sich die Krieger gegenseitig zu hauf ab.".</p>

<p>Von den wildesten Stämmen wird angenommen, dass sie immer noch Opferrituale durchführen - selten Gefangene anderer Stämme und Rassen, sondern oft Freiwillige aus ihren eigenen Reihen, die sich dem Opferdolch hingeben. Gerüchten nach glauben diese Stämme, dass ein solcher Tod die größte Ehre ist, die einem Krieger zuteil werden kann, da sie nach ihrem Tod mit Moshrans Segen in einem starken Körper wiedergeboren werden. Dieser Brauch, wie auch das "gegenseitige zu hauf Abschlachten", ist mittlerweile sehr selten geworden, da der Verlust starker Krieger und guter Jäger normalerweise ein großer Verlust für fast jeden Stamm ist. Für gewöhnlich werden heutzutage Tiere geschlachtet und den Göttern und Ahnen geopfert, ehe diese dann während den Festivitäten am Abend verspeist werden.

<p>Für viele Orks sind die Tage des Mas auch eine Zeit des Gedenkens eines ihrer größten Anführer in der Geschichte, Drokan Norotar. Er wird verehrt und ist hochangesehen als der Held und Märtyrer, der die friedlichen Orkstämme vereinte und den orkischen Völkern eine Stimme unter den anderen Rassen gab. Die Nachbarn seines Reiches trauten seinen friedlichen Absichten jedoch nicht und er wurde unter dem Vorwand von Verhandlungen gefangen genommen und ermordet. Das junge Reich zerbrach und was folgte, brachte den Orks großes Leid. Die Flammenorks verehren Drokan Norotar als Prophet, der den wilden Stämmen Frieden und Zivilisation brachte. Obwohl er selbst kein Flammenork war, hatten einige seiner Schriften großen Einfluss auf deren Kultur. Es gibt sogar eine Prophezeiung, nach der bald ein zweiter Drokan Norotar, oder gar eine Reinkarnation seiner Seele geboren werden soll, der die Stämme ein weiteres Mal vereinen wird. Um seine Erinnerung zu Ehren, schmieren sich die wilden Stämme der Orks Asche ins Gesicht und ritzen ihre Hände und Kopfhaut auf, um zu symbolisieren, wie Drokan Norotar geköpft wurde und seine Hände abgetrennt wurden. Mit Blut verschmierten Gesichtern stimmen sie während der gesamten fünf Tage des Mas Klagelieder und Elegien an.</p>

<p>Unter anderen Rassen hat das Fest oft die eher symbolische Tradition, bei der ohne viele Worte ein kleines Tier, normalerweise ein Hühnchen oder Hase geopfert wird. Dies wird in der Hoffnung getan, damit Moshran zu besänftigen und Kriege und Pech abzuwenden. Für gewöhnlich gibt es hierbei keine Gebete, sondern nur eine stille Geste. Nach dem Opfer verbleiben die Leute in ihren Häusern und hoffen, dass der Mas schnell vorbeizieht, sodass sie ein neues Jahr willkommen heißen können.</p>

</div>
<?php include_short_footer(); ?>