<?php
	include_once ( $_SERVER['DOCUMENT_ROOT'] . "/shared/shared.php" );
	create_XMLheader();
?>
<div>
	<h1>Siros</h1>

	<h2>Month of Love</h2>

<p>The month of Siros is named after Sirani, the goddess of love who is much celebrated by all races. All known cultures have loyalty and binding celebrations during the month of Siros and Sirani remains popular throughout Salkamar, Gynk and the Serinjahs. Mostly celebratory fairs or dances, they offer young couples the chance to meet and perhaps exchange marriage vows. There is no precise date for that festival but it is usually held around the 12th Siros. Often local officials arrange for a festival to be held in each village on a different day.</p>

<p>Although all celebrate, there are differences among the races and religions. In elven tradition the male attaches branches from the Mevranno tree to the entrance of his love's house. The Mevranno tree lives in symbiosis with the climbing Levrenni plant which wraps around trees when still young and blooms beautifully; alone neither plant can thrive. If an elfess accepts the offer she braids a Levrenni stem around the Mevrannon branch. Among the halflings it is the females who take the first step, placing a girdle of flowers on top of their love's head. If the man does not take it off, the offer is considered accepted. Human traditions are rather more complicated with great differences between cultures and often no real offer but more an expression of love. Things that might count as honourable and endearing in the one village could be seen as highly insulting behaviour in another. Most common is for the man to ask his love for a dance, but not all dances are for love. Should the woman be endeared to the man, she gives him a ribbon which was braided into her hair, as a traditional sign of affection. If the man binds the ribbon around his arm, he signals that he reciprocates her feeling.</p>

<p>Orcs are known for a somewhat rougher expression of their affection. Following their tradition the male secretly visits the house of the orcess with his comrades and "steals" her. This thievery is ritualistic so that there are usually no injuries received on each side, unless the orcess has previously rejected her suitor. Generally the female is brought immediately to the male's house, whilst her family gather outside to try to "save" her. If the "kidnapped" orcess opens the door and asks the family to come inside before the house is stormed the marriage offer is accepted. In lizard culture most weddings are arranged by the parents and the children are no voice so it is not unheard of for the festival to be the first time the couple meets. Parents make their agreements before the celebration and then the couple meet at the male's house before everyone proceeds to the temple to witness the marriage vows in front of a priest. In case of the dwarves, the local smith has an important spiritual role in the ceremony beyond the simple crafting of rings. A couple that wants to marry is "linked" by the smith who crafts two rings, forged from the same piece of metal, that interlink to form one when put together. Traditionally these rings are hung above the couple's bed, signifying their linkage and the strength their union brings.</p>

</div>
<?php include_short_footer(); ?>