<?php
   include $_SERVER['DOCUMENT_ROOT'] . '/shared/shared.php';

   Page::setTitle( 'Reiche' );
   Page::setDescription( 'Übersicht über die Spielwelt.' );
   Page::setKeywords( array( 'Welt', 'Illarion', 'Cadomyr', 'Galmair', 'Runewick' ) );

   Page::setXHTML();
   Page::Init();
?>
<h1>Die Welt Illarion</h1>

<center><a href="<?php echo Page::getURL(); ?>/general/de_map_of_illarion.jpg"><img width="600" height="497" src="<?php echo $url; ?>/general/de_bigthumb_map_of_illarion.jpg" alt="Karte von Illarion"/></a></center>

<h2><a name="1"></a>Cadomyr - Realm of Honour and Glory</h2>

<p>Hoch über den gezackten Gipfeln der Namenlosen Berge, verlässt ein Adler seinen Horst. Schneebedeckte Gipfel, die das Firmament durchbrechen, grenzen die Halbinsel ab und dominieren die tiefer liegenden Steppen, Wälder und Wüsten Illarions. Majestätisch kreist der Adler über dem Chaos unerklärlicher Wunder und undenkbaren Grauens, das sich unter ihm abspielt.</p>

<p>Aus der Hochebene Galmairs, fließt der Malachitstrom hinab auf die Narguns Ebene, um sich dem Mächtigen Strom anzuschließen. Tief versteckt in den Gebirgsausläufern und hinter verstärken Mauern, die sich mit den felsigen Ausläufern verbinden, liegt die Händlerstadt Galmair. Zahllose Eingänge führen in das Innere von Höhlen, Tunneln und Mienen, die tief in die Berge geschnitten sind - eine geschäftige Welt, die für den dahingleitenden Adler nur wenig Bedeutung hat. Im Norden der stinkenden Sümpfe erkennen die scharfen Augen des Adlers den Hafen Galmairs und die Eingänge zum Tempel der Fünf. Dort, wo das Land in der Syritabucht von den Wellen eingeschlossen wird, zieren weit verstreute Inseln den Horizont.</p>

<p>Die üppigen Grassteppen der Ebene der Stille dehnen sich weit nach Osten aus, bis hin zu den Nördlichen Wäldern, durchbrochen einzig durch den Syritakanal, der das Land auf seinem Fluss zum Mächtigen Strohm tief durchschneidet. Während der Adler schwerelos über die Wälder hinweggleitet, kreist er einige Male neugierig über der Lichtung, die als Rabans Hain bekannt ist. Weiter im Norden stößt der Vogel ein stechendes Kreischen aus, als er über den mächtigen Festungswänden des Unüberwindbaren Limes plötzlich abdreht, die die übrigen Teile der Halbinsel vom Rest abtrennen. Selbst in solch großer Höhe, wagt es der mächtige Adler nicht, in die Wolken über dem düster anmutenden, tiefen Wald einzudringen.</p>

<p>Die Wellen schlagen gegen die Ostküste, welche die Nördlichen Wälder abgrenzt und die felsigen Ausläufer, die als Fels des Bösen bekannt sind, steigen hoch aus dem Ozean auf und dominieren so die Landschaft am Horizont. Auf seinem Weg in Richtung Süden, fliegt der Adler weiter über den isolierten Nordhafen und die Schulterplatteninsel, mit ihren verstreuten Ruinen und unruhigen Friedhöfen. Aus dem Ozean erstreckt sich das Sumpfgebiet, in dem sich die Ruinen lange vergessener Tempel befinden und formt das nördliche Ufer des Mächtigen Stroms. Weiter landeinwärts, wo der Mächtige Strom und der Glühende Fluss im Spinnenmaul zusammenfließen, liegt auf einer Insel inmitten der sich hier überkreuzenden Routen zu allen drei Reicehn, der Gasthof zur Hanfschlinge.</p>

<p>Am Südufer des Mächtigen Stroms, grenzt der Todessumpf an die üppige Elstree Ebene und wird von einem mächtigen Berg beschattet, der nur für Igruks Höhle und die Gefahren in deren Inneren bekannt ist. Der Adler gleitet hoch über den mächtigen Bäumen des Elstreewaldes dahin, unberührt von vielen der mysteriösen Zauber, die sich unter den Baumkronen verbergen. Die Graslandschaft des Ostlandes trennt das rießige Waldgebiet von der windigen Küste. Vom isolierten Osthafen aus, fliegt der Adler zwischen den Zwillingsbergen und der für manche als Wunderland bekannten Kuriosität hindurch, ehe er auf die Morgentausümpfe zugleitet.</p>

<p>Die Stadt Runewick befindet sich, umgeben von fruchtbaren Feldern und üppigen Wiesen, inmitten eines Archipels waldiger Inseln. Der Adler gleitet über dem Flickenmuster aus verstreuten Gebäuden und Brücken dahin, den weisen Worten, die in die Bücher der Bibliotheken unter ihm geschrieben sind, ungewahr. Hinter der Lunordbrücke liegt die Bauernsiedlung, die als Eibental bekannt ist und der Hafen Runewicks, der sich am Eingang zur Schlangenkopfbucht befindet. Jenseits des plätschernden Bachs, findet man die Bärenhöhle und die sanften Hügel der Frohen Wiesen.</p>

<p>Der Adler steigt scharf auf und macht einen weiten bogen um den Drachenhort, wohl wissend um die Macht, die sich in dessen Inneren verbirgt. Lava fließt aus dem Vulkan und zerstört das Land entlang der nördlichen Flanke der Berge. Das faulige Sumpfland des Todesgestanks breitet sich bis zu den Dreifingerspitzen aus, die in die Schlangenkopfbucht hineinragen. Weiter entlang der Schlangenkopfküste, ragt der Schlangenkopfberg in die Höhe und überblickt die Bucht und die zahlreichen, verstreuten Inseln darin.</p>

<p>Weiter Richtung Norden, auf die Grenzberge zufliegend, entdecken die scharfen Augen des Adlers die Elfenruinen, die zwischen den Bäumen versteckt liegen. In den Bergen liegen die Eingänge zu Cherass Zitadelle und der Glitzernden Höhle. Der Adler dreht ab und fliegt gegen den Lauf des Glühenden Flusses auf seinem Weg durch die Ostflanke der Grenzberge. Im Schatten der felsigen Ausläufer, fliegt der Adler ungehindert über die Schneise der Verwüstung hinweg, die als Todesschneise bekannt ist. Wasser quillt aus der Leuchtenden Pforte und durchschneidet den Lavafluss im Leuchtenden Wald darunter und die darüber aufsteigenden Dämpfe hüllen die krummen Überreste eines längst abgestorbenen Waldes ein. Während der Adler über den Wichtelmannkanal und den lodernden Flammenwall fliegt, zieht er neugierig Kreise über den Ruinen, die sich entlang der westlichen Küste der Schlangenkopfbucht befinden, wo das einzige noch intakte Gebäude der Leuchtturmhafen zu sein scheint.</p>

<p>Von den südlichsten Gebirgsausläufern aus, gleitet der Adler über dem Wachwald dahin, der sich schützend an der Westküste der Schlangenkopfbucht ausbreitet und über den Baumwipfeln abdrehend, zieht der Adler entlang der Küste zurück, wo die Einsamen Inseln, weit draußen auf dem mächtigen Ozean, den Horizont zieren. Dort, wo sich die Grenzberge im Süden bis in die Namenlosen Berge erstrecken, bilden sie die östliche Grenze zur Kantabiwüste. Zahlreiche Höhleneingänge zeichnen die Berglandschaft und deuten auf die Biester und Kriminellen hin, die in ihnen Zuflucht finden. Tief unter den Bergen vergraben, liegt jedoch das Schattenland, dessen Schrecken dem dahingleitenden Adler unbekannt sind.</p>

<p>Im Südwesten Illarions, herrscht die Kantabiwüste vor, die sich von den Bergen bis zum Ozean erstreckt. Der Adler fliegt über den verlassenen Gebieten hinweg, die mit den Ruinen von Siedlungen und lange verlassenen Arbeitslagern übersäht sind, die auf bessere Zeiten hindeuten, ehe Kriminelle sich dort wie die Kakerlaken ausbreiteten. Irgendwo aus den Höhen der Namenlosen Berge quellend, schneidet der Kantabifluss durch dei Wüste, auf seinem Weg in Richtung des Großen Ozeans, wo er auseinander fließt und das fruchtbare Kantabidelta bildet. Der ominöse Berg Letma erstreckt sich dort in die Höhe und überblickt das Delta und die Katainsel, während die Wellen des Großen Ozeans an seinen felsigen Ausläufern zerschellen.</p>

<p>Während der Adler abdreht und die Küste entlang fliegt, kommt er am nunmehr Verlorenen Hafen vorbei und überquehrt die Mündung mit dem neuen Hafen Cadomyrs. Weiter im Norden liegt das Kapp des Abschieds und Fabers Wachhaus dient als letzter Aussichtspunkt zur Piratenbucht. Flankiert von den unüberwindbaren Namenlosen Bergen und dem Großen Ozean, erheben sich Cadomyrs Unheil verkündende, einheitlichen Festungswälle aus dem goldenen Sand und reflektieren die brennend heißen Strahlen der Wüstensonne. Banner wehen stolz von den Zinnen und wachen über die Monumente der glorreichen Taten vergangener Herrscher, während der Adler, unberührt von der unter ihm befindlichen Hierarchie, über ihnen hinweggleitet.</p>

<p>In majestätischem Flug, zieht der Adler über die Wipfel und Bergspitzen zurück zu seinem Horst. Von seiner luftigen Perspektive aus, blickt er unberührt auf Eiffersucht, Verrat und Neid herab, die die Machtkämpfe zwischen den Reichen antreiben. Jeden Tag zieht er über Illarion seine Kreise und beobachtet alles, das passiert und bleibt dabei doch stets außerhalb der Reichweite des Chaos, das unter ihm herrscht. Einige behaupten, die Götter würden über uns wachen, aber die Meisten sind zu beschäftigt mit ihren eigenen Problemen, um den aufsteigenden Adler zu bemerken.</p>

<?php Page::insert_go_to_top_link(); ?>